### ISSUE TITLE
Upgrading to ruby 3 causes the initializer to unproperly handle auto-injected args 

### ISSUE THREAD

**Issue by alex-damian-negru** [dry-rb/dry-initializer#82]
## Describe the bug

While upgrading an app from Ruby 2.6.6 to 3.0.0, our repos crashed with:

```
KeyError: Api::Organizations::Repositories::Organization: option 'container' is required
from (eval):4:in `block in __dry_initializer_initialize__'
```

Here's a stack trace from a test:

```ruby
1) Api::Organizations::Repositories::Organization#create creates a new organization
     Failure/Error: let(:repository) { described_class.new }

     KeyError:
       Api::Organizations::Repositories::Organization: option 'container' is required
     # (eval):4:in `block in __dry_initializer_initialize__'
     # (eval):4:in `fetch'
     # (eval):4:in `__dry_initializer_initialize__'
     # /bundle/vendor/ruby/3.0.0/gems/dry-initializer-3.0.4/lib/dry/initializer/mixin/root.rb:7:in `initialize'
     # /bundle/vendor/ruby/3.0.0/gems/rom-repository-5.2.2/lib/rom/repository.rb:111:in `initialize'
     # /bundle/vendor/ruby/3.0.0/gems/rom-repository-5.2.2/lib/rom/repository/root.rb:62:in `initialize'
     # /bundle/vendor/ruby/3.0.0/gems/dry-auto_inject-0.7.0/lib/dry/auto_inject/strategies/args.rb:59:in `initialize'
     # /bundle/vendor/ruby/3.0.0/gems/rom-repository-5.2.2/lib/rom/repository/class_interface.rb:62:in `new'
     # /bundle/vendor/ruby/3.0.0/gems/rom-repository-5.2.2/lib/rom/repository/class_interface.rb:62:in `new'
     # /bundle/vendor/ruby/3.0.0/gems/dry-auto_inject-0.7.0/lib/dry/auto_inject/strategies/args.rb:20:in `block (2 levels) in define_new'
     # ./spec/api/organizations/repositories/organization_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./spec/api/organizations/repositories/organization_spec.rb:15:in `block (4 levels) in <top (required)>'
     # ./spec/api/organizations/repositories/organization_spec.rb:15:in `block (3 levels) in <top (required)>'
```

That repo inherits a base repo in which the container is auto-injected:

```ruby
include Import.args['persistence.schemas.public']
```

## To Reproduce

```ruby
require 'rom'
require 'dry/container'
require 'dry/auto_inject'
require 'sqlite3'

rom = ROM.container(:sql, 'sqlite::memory')
container = Dry::Container.new
container.register(:rom, rom)

Import = Dry::AutoInject(container)

class Repository < ROM::Repository::Root
  include Import.args[:rom]
end

Repository.new
```

## Expected behavior

The container should be properly injected & no error should be raised when doing `Repository.new`.

## My environment

- Affects my production application: NO
- Ruby version: 3.0.0
- OS: Pop!_OS 20.10

**Comment by flash-gordon** [comment]
Newer versions of ROM prefer injecting via keywords, pls try `include Import[container: 'rom']`

**Comment by alex-damian-negru** [comment]
That worked, thanks a lot! Closing the issue.
