### ISSUE TITLE
README code not working

### ISSUE THREAD

**Issue by joevandyk** [dry-rb/dry-initializer#9]
```
require 'dry-initializer'

class User
  extend Dry::Initializer::Mixin

  param  :name,  type: String
  param  :role,  default: proc { 'customer' }
  option :admin, default: proc { false }
end
```

```
/Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-initializer-0.4.0/lib/dry/initializer/plugins/type_constraint.rb:9:in `call': String used as constraint for argument 'name' is not a dry-type. (Dry::Initializer::Errors::TypeConstraintError)
	from /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-initializer-0.4.0/lib/dry/initializer/plugins/base.rb:18:in `call'
	from /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-initializer-0.4.0/lib/dry/initializer/builder.rb:53:in `block in define'
	from /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/set.rb:306:in `each_key'
	from /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/set.rb:306:in `each'
	from /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-initializer-0.4.0/lib/dry/initializer/builder.rb:53:in `map'
	from /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-initializer-0.4.0/lib/dry/initializer/builder.rb:53:in `define'
	from /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-initializer-0.4.0/lib/dry/initializer/mixin.rb:16:in `param'
	from test.rb:6:in `<class:User>'
	from test.rb:3:in `<main>'
```

**Comment by nepalez** [comment]
@joevandyk The thing is that dry-initializer from v0.4.0 does not support plain types, only dry-types.

Your example could be re-writtten as

```
require 'dry-initializer'
require 'dry-types'

module Types
   include Dry::Types.module
end

class User
  extend Dry::Initializer::Mixin

  param  :name,  type: Types::Coercible::String
  param  :role,  default: proc { 'customer' }
  option :admin, default: proc { false }
end
```

tbh, I updated docs on dry-rb.org, but had not published them yet.

**Comment by joevandyk** [comment]
well publish them then ;)
